version: "3.3"
services:
  test.py36:
    build:
      context: .
      dockerfile: Dockerfile.py36
    volumes:
      - ./:/apprise

  test.py310:
    build:
      context: .
      dockerfile: Dockerfile.py310
    volumes:
      - ./:/apprise

  rpmbuild.el8:
    build:
      context: .
      dockerfile: Dockerfile.el8
    volumes:
      - ./:/apprise

# Connect to web and create a new project using the manage script
# -> docker-compose run --rm test.py36 bash
# bin/apprise -
# bin/checkdone.sh
#
# Run a set of tests for just a certain section
#  docker-compose run --rm test.py36 bin/test.sh fcm
#
# Or just run all the tests in python 3.6
#  docker-compose run --rm test.py36 bin/test.sh
#
# Want to run the whole test suite:
#
# [ -f .coverage ] && rm -f .coverage
# docker-compose run --rm test.py36 coverage run --append -m pytest -vv
# docker-compose run --rm test.py310 coverage run --append -m pytest -vv
#
# # Now produce a report
# docker-compose run --rm test.py310 coverage report --show-missing

## RPM Building
# el8
#  - docker-compose run --rm rpmbuild.el8 build-rpm.sh
